apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-01
spec:
  storageClassName: "oci"
  selector: 
    matchLabels:
      oci-availability-domain: "US-ASHBURN-AD-1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
