apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: route-rules
spec:
  destination:
    name: aura-js-creditscore
  precedence: 1
  route:
# Default routing rule 50:50
# To route traffic to v2 only change weight to 100 and 0 OR 100 and comment out v1 label section (last 3 lines)
  - labels:
      version: v2
    weight: 50
  - labels:
      version: v1
    weight: 50
